AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Telegram Sender Bot

Globals:
  Function:
    Runtime: python3.12
    Timeout: 300
    MemorySize: 512

Resources:
  TelegramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        SecretsManagerReadWrite
      Events:
        DailySchedule:
          Type: Schedule
          Properties: 
            Schedule: cron(45 9 * * ? *)